# **Homework 2**

## **Basis of Numpy Library**

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object and tools for working with these **arrays**.

To use Numpy, we first need to import the `numpy` package:

In [1]:
# import library
import numpy as np

### **Arrays**

- A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers.

- The number of dimensions is the rank of the array;

- The shape of an array is a tuple of integers giving the size of the array along each dimension.

**Exercise:**
- What is an **array**?
- Give an example that can be represented by an array.

In [2]:
# create 1d array
array1D = np.array([1, 2, 3, 4 ,5])

print(f"The variable type of array1D is a ${type(array1D)}, the dimension of it is ${array1D.ndim}")
# print(f"The type of variable array1 is ${typeof(array1)}")

The variable type of array1D is a $<class 'numpy.ndarray'>, the dimension of it is $1


In [3]:
# print shape
print(f"The shape of array1D is ${array1D.shape}")

The shape of array1D is $(5,)


In [4]:
# create 2d array
temp = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
array2D = temp.reshape(-1, 2)

In [5]:
# print shape
print(f"The shape of array2D is ${array2D.shape} with ${array2D.ndim} dimensions")

The shape of array2D is $(5, 2) with $2 dimensions


In [6]:
# create 3d array
array3D = np.zeros((3, 3, 3))

In [7]:
# print shape
print(f"The shape of array3D is ${array3D.shape}")

The shape of array3D is $(3, 3, 3)


### **Array Indexing**

In [8]:
# print the second element in your 1d array
print(f"the second item in array1D is ${array1D[1]}")

the second item in array1D is $2


In [9]:
# print the first row second element in your 2d array
print(f"The first row second element in array2D is ${array2D[0][1]}")

The first row second element in array2D is $2


In [10]:
# print the first rank first row second element in your 3d array
print(f"The first rank first row second element in array3D is ${array3D[0][0][1]}")

The first rank first row second element in array3D is $0.0


### **Array Operations**

In [11]:
# create 2 2d-array
newArray2D1 = np.array([1, 2, 3, 4, 5, 6, 7, 8]).reshape(-1, 2)
newArray2D2 = np.array([9, 10, 11, 12, 13, 14, 15, 16]).reshape(-1, 2)
# print(newArray2D)

# Elementwise sum; both produce an array
sum1 = newArray2D1 + newArray2D2
sum1_alt = np.add(newArray2D1, newArray2D2)
print(sum1)
print(sum1_alt)


[[10 12]
 [14 16]
 [18 20]
 [22 24]]
[[10 12]
 [14 16]
 [18 20]
 [22 24]]


In [12]:
# Elementwise difference; both produce an array
diff = newArray2D1 - newArray2D2
diff_alt = np.subtract(newArray2D1, newArray2D2)
print(diff)
print(diff_alt)

[[-8 -8]
 [-8 -8]
 [-8 -8]
 [-8 -8]]
[[-8 -8]
 [-8 -8]
 [-8 -8]
 [-8 -8]]


In [13]:
# Elementwise division; both produce an array
print(newArray2D1 / newArray2D2)
print(np.divide(newArray2D1, newArray2D2))

[[0.11111111 0.2       ]
 [0.27272727 0.33333333]
 [0.38461538 0.42857143]
 [0.46666667 0.5       ]]
[[0.11111111 0.2       ]
 [0.27272727 0.33333333]
 [0.38461538 0.42857143]
 [0.46666667 0.5       ]]


In [14]:
# Elementwise product; both produce the array
print(newArray2D1 * newArray2D2)
print(np.multiply(newArray2D1, newArray2D2))


[[  9  20]
 [ 33  48]
 [ 65  84]
 [105 128]]
[[  9  20]
 [ 33  48]
 [ 65  84]
 [105 128]]


In [15]:
# Dot product or matrix multiplication
newArray2D3 = np.random.rand(2, 3)
print(f"newArray2D1:\n ${newArray2D1}")
print(f"newArray2D3:\n ${newArray2D3} ")
print(f"\n===============================\n")
print(newArray2D1.dot(newArray2D3))
print(np.dot(newArray2D1, newArray2D3))

newArray2D1:
 $[[1 2]
 [3 4]
 [5 6]
 [7 8]]
newArray2D3:
 $[[0.48528278 0.55898771 0.22493603]
 [0.21366216 0.9685593  0.33880297]] 


[[ 0.91260709  2.49610631  0.90254196]
 [ 2.31049696  5.55120032  2.03001996]
 [ 3.70838683  8.60629433  3.15749795]
 [ 5.1062767  11.66138835  4.28497594]]
[[ 0.91260709  2.49610631  0.90254196]
 [ 2.31049696  5.55120032  2.03001996]
 [ 3.70838683  8.60629433  3.15749795]
 [ 5.1062767  11.66138835  4.28497594]]


## Basis of OpenCV

In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


In [2]:
# read file
import cv2
# from google.colab.patches import cv2_imshow

filename = '/Users/icesplendent/Desktop/DL_biotech/Hw/Hw2/hw2_image.png' # your file path


In [3]:
# Rotate
image = cv2.imread(filename)

# check the image
# cv2.imshow('initial', image)
# k = cv2.waitKey(1)

# check the format
print(image.shape)

# do the rotation
(h, w, d) = image.shape
center = (h//2, w//2)

R = cv2.getRotationMatrix2D(center, 180, 1.0)  # params: center, angle, scale
rotat_img = cv2.warpAffine(image, R, (w, h))

# Show the Rotated Picture
cv2.imshow("Rotated", rotat_img)
cv2.waitKey(1)

(1024, 1024, 3)


-1

In [7]:
# To close the windows
cv2.destroyAllWindows()
# cv2.destroyWindow("Rotated")
for i in range (1,5):
    cv2.waitKey(1)

In [10]:
# Denoise by filter
def gaussian_kernel(size, sigma):
    kernel = np.fromfunction(
        lambda x, y: (1 / (2 * np.pi * sigma**2)) * np.exp(
                -((x - ((size - 1) / 2)**2) + y - ((size - 1) / 2)**2) / (2 * sigma**2)
            ),
        (size, size)
    )
    return kernel


# denoised_img = cv2.filter2D(rotat_img, -1, gaussian_kernel(5, 3.1))
# denoised_img = cv2.GaussianBlur(rotat_img, (5, 5), 1)
denoised_img = cv2.medianBlur(rotat_img, 7)
combined_image = np.hstack((image, denoised_img))
cv2.imshow("Initial (left) and denoised (right)", combined_image)
cv2.waitKey(1)

cv2.imwrite("/Users/icesplendent/Desktop/DL_biotech/Hw/handin_purpose/Hw2/112066701_王柏涵_HW2.png", denoised_img)

True